### Index
GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
### Show
GET http://localhost:7000/products/5a2743d514cfb11fad6580a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
### New
POST http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
### Update
PATCH http://localhost:7000/products/5a2743d514cfb11fad6580a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
Content-Type: application/json

{
  "brandName": "Microsoft",
  "name": "Wireless mouse"
}
### Delete
DELETE http://localhost:7000/products/5a2743d514cfb11fad6580a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY

### Register User
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "newemail@gmail.com",
  "firstName": "Alessio",
  "lastName": "Palumbo",
  "password": "123456"
}

### Sign In
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "newemail@gmail.com",
  "password": "123456"
}

### Wishlist
GET http://localhost:7000/wishlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
### Add to Wishlist
POST http://localhost:7000/wishlist/products/5a2b4e7be47f566a9917a744
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
###m Delete from Wishlist
DELETE http://localhost:7000/wishlist/products/5a2b4e7be47f566a9917a744
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY
