GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMjU5NjAwNSwiZXhwIjoxNTEzMjAwODA1LCJzdWIiOiI1YTI4NjIyNDJmZWMwODBlZmY2N2MzOTkifQ.8IQdTm21ky0uMJ90vLYSRALOc7CXgo3eFpflHuiaXUY

### Register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "newemail@gmail.com",
  "firstName": "Alessio",
  "lastName": "Palumbo",
  "password": "123456"
}

### Sign In
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "newemail@gmail.com",
  "password": "123456"
}