### variables
@base_url = https://yarra-api-jbdangrxae.now.sh
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTUxMzIxMTM5OCwiZXhwIjoxNTEzODE2MTk4LCJzdWIiOiI1YTMxYzYwNTUzZjFhZjAwOTlhZjI5NzQifQ.dDOSocq6SQHQLvP5B7WEQvGaCVqFBGMxy3rUgzwHyrk

### List products
GET {{base_url}}/products

### Create products
POST {{base_url}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "brandName": "Lg",
  "name": "G6",

}

### Sign up
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "newemail@gmail.com",
  "firstName": "Alessio",
  "lastName": "Palumbo",
  "password": "123456"
}

### Add Category
POST {{base_url}}/categories
Authorization: Bearer {{token}}
Content-type: application/json

{
  "categoryName": "Sport"
}